INSERT INTO `songs` (`artist`, `title`, `video_mix_id`) VALUES
('Lil Jon Ft. E-40', 'Snap Ya Fingas', 211),
('Yung Joc Ft. Nitti', ' It\'S Goin\' Down', 211),
('Nelly', ' E.I.', 211),
('Cali Swag District', ' Teach Me How To Dougie', 211),
('Slim Ft. Yung Joc', ' So Fly', 211),
('Chingy', ' Balla Baby', 211),
('Dr. Dre Ft. Snoop Dogg', ' Still Dre', 211),
('Eve Ft. Alicia Keys', ' Gangsta Lovin\'', 211),
('', ' Always On', 211),
('Every Little Step', 'Bobby Brown', 212),
('Soul Ii Soul', ' Back To Life', 212),
('One Way', ' Cutie Pie', 212),
('Tom Tom Club', ' Genuis Of Love', 212),
('Nu Shooz', ' I Can\'T Wait', 212),
('George Benson', ' Turn Your Love Around', 212),
('Keith Sweat', ' I Want Her', 212),
('Timex Social Club', ' Rumors', 212),
('Shalamar', ' Night To Remember', 212),
('', ' Can', 212),
('Cassidy Ft. R. Kelly', 'Hotel', 213),
('Camila Cabello', ' Crying In The Club', 213),
('Fifth Harmony Ft. Fetty Wap', ' Flex', 213),
('The Chainsmokers Ft. Halsey', ' Closer', 213),
('Vanessa Carlton', ' A Thousand Miles', 213),
('Enrique Iglesias Ft. Sean Paul', ' Bailando', 213),
('Shaggy', ' It Wasn\'T Me', 213),
('Malum', ' Felices Los 4', 213),
('The Deele', 'Two Occassions', 214),
('Keithsweat Ft. Pretty Russ & Kut Close', ' Twisted', 214),
('Tony, Toni,Tone', ' Anniversary', 214),
('Freddie Jackson', ' Have You Ever Loved Somebody', 214),
('Tevin Campbell', ' I\'M Ready', 214),
('Levert', ' Casanova', 214),
('Chuckii Booker', ' Turned Away', 214),
('New Edition', ' If It Isn\'T Love', 214),
('Pussy Cat Dolls Ft. Busta Rhymes', 'Don\'T Cat', 215),
('Move Ya Body', ' Nina Sky', 215),
('Lady Gaga', ' Poker Face', 215),
('Kesha', ' Tik-Tok', 215),
('Nicki Minaj', ' Pound The Alarm', 215),
('Katy Perry', ' Teenage Dream', 215),
('Black Eyed Peas', ' Rock That Body', 215),
('Far East Movement Ft. Dev', ' Like A G6', 215),
('Pitbull Ft. T', ' Party', 215),
('Pitbull Ft. Ne-Yo', 'Time Of Our Lives', 216),
('Avicii', ' Levels', 216),
('Chris Brown', ' Yeah 3X', 216),
('Flo-Rida Ft. T-Pain', ' Low', 216),
('Don Omar & Lucenzo', ' Danza Kuduro', 216),
('Shaft', ' Mambo', 216),
('Blackout All Stars', ' I Like It Like That', 216),
('Rihanna', ' We Found Love', 216),
('Lmfao', ' Party Rock Anthem', 216),
('', ' My Boo [Tom Bud', 216),
('T.L.C.', 'Creep', 217),
('Soul 4 Real', ' Candy Rain [Rmx]', 217),
('112 Ft. Notorious B.I.G., Mase', ' Only U [Rmx]', 217),
('Brandy Ft. Monica', ' The Boys Is Mine', 217),
('Nivea Ft. Brian Casey', ' Don\'T Mess With My Man', 217),
('Mya', ' Ex', 217),
('Mark Morrison', ' Return Of The Mack', 217),
('Mariah Carey Ft. Ol\' Dirty ', ' Fantasy', 217),
('Usher Ft. Pitbull', 'Dj\'S Got Us Fallin In Love', 218),
('Don Omar & Lucenzo', ' Danza Kuduro', 218),
('Flo-Rida Ft. Sia', ' Wild Ones', 218),
('Journey', ' Don\'T Stop Believing', 218),
('Whitney Houston', ' I Wanna Dance With Somebody', 218),
('Bruno Mars', ' That\'S What I Like', 218),
('Dnce', ' Cake By The Ocean', 218),
('', ' This Is What', 218),
('Becky G Ft. Bad Bunny', 'Mayores', 219),
('Dady Yankee', ' Dura', 219),
('Maluma Ft. Nego De Borel', ' Corazion', 219),
('Luis Fonsi & Daddy Yankee Ft. Justin Bieber', ' Despacito', 219),
('Big Pun Ft. Joe', ' Stilll Not A Player [Moomba Rmx]', 219),
('Ozuna Ft. Cardi B.', ' La Modelo', 219),
('Camila Ca', ' Havana [Moombah Rmx]', 219),
('Pat Benatar', 'Love Is A Battlefield', 220),
('George Michaels', ' Faith', 220),
('Starship', ' Nothings Gonna Stop Us Now', 220),
('Toto', ' Poor Georgie', 220),
('Rufus & Chaka Khan', ' Ain\'T Nobody', 220),
('Bananarama', ' Cruel Summer', 220),
('Kajagoogoo', ' Too Shy', 220),
('Mathew Wilder', ' Break My Stride', 220),
('U2', ' With Or Without You', 220),
('', ' ', 220),
('Childish Gambino', 'Redbone', 221),
('Khalid', ' Location', 221),
('Ed Sheeran', ' Shape Of You', 221),
('Major Lazer Ft. Dj Snake, M0', ' Lean On', 221),
('Justin Bieber', ' Sorry', 221),
('Dupa Lipa', ' Idgaf', 221),
('Sza', ' The Weekend [Funk Wav Rmx]', 221),
('Beyonce', ' Love On Top', 221),
('T.L.C.', ' Scrubs', 221),
('Charlie Puth', ' Attention', 221),
('', ' Wild Thoug', 221),
('Dion', 'Runaround Sue', 222),
('The Beach Boys', ' Surfin\' U.S.A.', 222),
('Chuck Berry', ' Johnny B. Good', 222),
('Nancy Sinatra', ' These Boots Are Made For Walking', 222),
('Ray Charles', ' Hit The Road Jack', 222),
('The Champs', ' Tequila', 222),
('The Contours', ' Do You Love Me', 222),
('Elvis Presley', ' All Shook Up', 222),
('', ' It\'S My Party', 222),
('Ying Yang Twins', 'Salt Shaker', 223),
('Juvenile', ' Back That Thang Up', 223),
('Big Sean Ft. E-40', ' Idfwu', 223),
('Ty Dolla Sign Ft. E-40', ' Saved', 223),
('Remy Boyz', ' 679', 223),
('Trinidad James Ft. Mystikal, Lil Dicky', ' Just A Lil Thick', 223),
('Akon Ft. Snoop Dogg', ' I Wanna Love You', 223),
('Zedd Ft. Alessia Car', ' Stay', 223),
('Aaron Hall', 'Don\'T Be Afraid', 224),
('Bobby Brown', ' In Control', 224),
('Janet Jackson', ' Love Will Never Do With Out You', 224),
('Wreckx-N-Effect', ' Rump Shaker', 224),
('Karyn White', ' The Way You Love Me', 224),
('T.L.C.', ' Hat 2 Da Back', 224),
('Heavy D. & The Boyz', ' Is It Good To You', 224),
('Portrait', ' Here We Go', 224),
('', ' I\'M D', 224),
('New Edition', 'N.E. Heartbreak', 225),
('Soul Ii Soul', ' Back To Life', 225),
('Jasmine Guy', ' Another Like My Lover', 225),
('Heavy D. & The Boyz Ft. Al B. Sure', ' Somebody For Me', 225),
('T.L.C.', ' What About Your Friends', 225),
('Tony, Toni, Tone', ' If I Had No Loot', 225),
('Mac Band Ft. The Mc Campb', ' Roses Are Red', 225),
('Al B. Sure', 'Nite And Day', 226),
('Blackstreet', ' Booty Calli', 226),
('S.W.V', ' I\'M So Into You', 226),
('Hi Five', ' I Like The Way', 226),
('Father Mc', ' Treat Them Like You Wanted To Be Treated', 226),
('Joe Public', ' Live And Learn', 226),
('Bell, Biv, Devo', ' Do Me', 226),
('Today', ' Why You Getting\' Funky On Me', 226),
('', ' Rub You The R', 226),
('Al B. Sure', 'Nite And Day', 227),
('Blackstreet', ' Booty Calli', 227),
('S.W.V', ' I\'M So Into You', 227),
('Hi Five', ' I Like The Way', 227),
('Father Mc', ' Treat Them Like You Wanted To Be Treated', 227),
('Joe Public', ' Live And Learn', 227),
('Bell, Biv, Devo', ' Do Me', 227),
('Today', ' Why You Getting\' Funky On Me', 227),
('', ' Rub You The R', 227),
('Ruff Ryders Ft. Eve N Nokio', 'What Ya Want', 228),
('Mase Ft. Total', ' What You Want', 228),
('Eric Bellinger', ' I Don\'T Want Her', 228),
('2 Pac Ft. Kc & Jojo', ' How Do U Want It', 228),
('Jason Derulo', ' Want To Twant Me', 228),
('5 Seconds Of Summer', ' Want You Back', 228),
('50 Cent', ' Just A Lil Bit', 228),
('Ross', ' All I Want', 228),
('Alessia Cara', 'Scars To Your Beautiful', 229),
('Diplo', ' Stay Open', 229),
('Rihanna Ft. Tory Lanez', ' Wild Thoughts', 229),
('Steve Aoki Ft. Ajr, Lil\' Yachty', ' Good Pretender', 229),
('Ginuwine', ' Pony', 229),
('Lady Bee Ft. Rochelle', ' Return Of The Mack', 229),
('Sjur Ft. Chris Crone', ' Let Me Love You', 229),
('Camil', ' Havana', 229),
('Salt N\' Peppa', 'Express Yourself', 230),
('Digital Underground', ' Humpty Dance', 230),
('L.L. Cool J.', ' Mama Said Knock You Out', 230),
('Dougie Fresh Ft. Slick Rick', ' The Show', 230),
('Umc\'S', ' Blue Cheese', 230),
('Sir Mix A Lot', ' Beepers', 230),
('De La Soul', ' Me Myself And I', 230),
('Mac Dre', ' California Livin\'', 230),
('', ' Be True T', 230),
('Wham', 'Everything She Want\'S', 231),
('New Order', ' Bizzare Love Triangle', 231),
('When In Rome', ' The Promise', 231),
('Cindy Lauper', ' Girl\'S Just Wanna Have Fun', 231),
('Denice Williams', ' Let\'S Hear It For The Boys', 231),
('Whitney Houston', ' How Will I Know', 231),
('Jerm', ' We Don\'T Have To Take Our Clothes Off', 231),
('Earth Wind & Fire', 'Let\'S Groove Tonight', 232),
('Mary Jane Girls', ' Candyman', 232),
('The Gap Band', ' Dropped A Bomb On Me', 232),
('Rick James', ' Superfreak', 232),
('Chic', ' Le Freak', 232),
('Anita Ward', ' Ring My Bell', 232),
('Lipps Inc.', ' Funky Town', 232),
('Frankie Smith', ' Double Dutch Bus', 232),
('Prince', ' Uptown', 232),
('', ' Off The Wall-', 232),
('Rozes & Nicky Romero', 'Where Would We Be', 233),
('Elli Mai', ' Boo\'D Up', 233),
('Russ', ' Wife You Up', 233),
('G-Eazy Ft. Yo Gotti', ' 1942', 233),
('Meek Mills', ' 1942 Flows', 233),
('Jacquees Ft. Dej Loaf', ' At The Club', 233),
('Jeremih Ft. Ty Dolla Sign', ' In The Light', 233),
('Dj Mustard Ft. Rjmrla & Rae Sremmurd', ' Hard Way', 233),
('', ' ', 233),
('Drake', 'Back To Back', 234),
('Sob X Rbe Ft. Yhung T.O.', ' Anti', 234),
('Asap Rocky, Nicki Minaj', ' Plain Jane', 234),
('Rae Sremmurd Ft. Juicy J.', ' Powerglide', 234),
('Migos', ' Stir Fry', 234),
('Marshmellow Ft. Anne Marie', ' Friends', 234),
('The Weeknd Ft. Kendrick Lamar', ' Pray For Me', 234),
('Panjabi M', ' Beware Of The Boys', 234),
('Yung Joc', 'I Know U See It', 235),
('Rich Boy Ft. Polow Da Don', ' Throw Some D\'S', 235),
('Nelly Ft. Paul Wall', ' Grillz', 235),
('Paul Wall', ' Back Then', 235),
('Lil Jon Ft. E-40', ' Snap Ya Fingers', 235),
('Young Jeezy Ft. Manie Fresh', ' And Then What', 235),
('T.I. Ft. Rihanna', ' Live Your Life', 235),
('David Ban', ' Get Like Me', 235),
('', 'Girls like you/Maroon 5', 236),
('', 'Real Rich /Wiz Khalifa featuring Gucci Mane', 236),
('', 'Pineapple/ Ty Dolla Sign fearturing Gucci Mane', 236),
('', 'Fly/ Marshmello ft Duck Tales', 236),
('', 'Ocean/ Martin Garrix ft Khalid', 236),
('', 'Hey Up There/ Buddy ft Ty Dolla Sign', 236),
('', 'Anywhere/ Dj Mustard ft Nick Jonas', 236),
('', 'Happy Wi', 236),
('Gucci Mane Ft. Migos', 'I Get The Bag', 237),
('Blocboy Ft. Drake', ' Look Alive', 237),
('Post Malone Ft. Ty Dolla Sign', ' Pyscho', 237),
('J.Lo Ft. Dj Khaled & Cardi B', ' Dinero', 237),
('Bad Bunny, Prince Riyce & J. Balvin', ' Sensuaildad', 237),
('Ozuna Ft. Bad Bunny, Winsin & Almighty', ' Solita', 237),
('', ' I Like It Lik', 237),
('Lionel Richie', 'All Night Long', 238),
('Phil Collins', ' In The Air', 238),
('Pink Floyd', ' Another Brick In The Wall', 238),
('Dobbie Bros.', ' Long Train Running', 238),
('Nelly Furtado Ft. Timbaland', ' Promiscuous', 238),
('Ciara Ft. Missy Elliott', ' 1,2 Step', 238),
('Sean Kingston', ' Take You There', 238),
('J', ' Want To Want Me', 238),
('Britney Spears', 'Sometimes', 239),
('98 Degrees', ' The Hardest Thing', 239),
('Backstreet Boys', ' Quit Playing Games With My Heart', 239),
('Smash Mouth', ' All Star', 239),
('Sugar Ray Ft. Supa Cat', ' Fly', 239),
('Paul Okenfield Ft. Shifty', ' Starry Eyed Surprise', 239),
('Hanson', ' Mmmbop', 239),
('Third Eye B', ' Semi Charmed Life', 239),
('Nicole Reene', 'Strawberries', 240),
('Lenny Kravitz', ' I Belong To You', 240),
('702', ' Where My Girls At', 240),
('Keyshia Cole Ft. A Mina', ' Shoulda Let You Go', 240),
('S.W.V.', ' Right Here', 240),
('Allure Ft. Nas', ' Head Over Heels', 240),
('Mya Ft. Jay-Z', ' Best Of Me Pt.2', 240),
('Desntiny\'S Child', ' No,No,No Pt.2', 240),
('', ' Don\'T Mes', 240),
('Arrested Development Nuthing But A G', 'Everyday People', 241),
('A Tribe Called Quest', 'Bonita Applebum', 242),
('The Fugees', ' Killing Me Softky', 242),
('Notorious B.I.G. Ft. Total', ' One More Chance [Rmx]', 242),
('Common Sense', ' I Used To Love H.E.R', 242),
('Outkast Ft. Babyface', ' Jazzy Belle', 242),
('Ice Cube', ' We Be Clubbin', 242),
('Busta Rhymes', ' Woo Hah', 242),
('L.L. C', ' Doin\' It', 242),
('Calvin Harris', 'Summer', 243),
('Clean Bandit Ft. Zara Larson', ' Symphony', 243),
('Calvin Harris Ft. John Newman', ' Blame', 243),
('Borgeous', ' Invincible', 243),
('David Guetta Ft. Nicki Minaj & Lil Wayne', ' Light Up My Body', 243),
('Selena Gomez & Marshmello', ' Wolves', 243),
('Drake', ' God\'S Plan', 243),
('Jay-Z Ft. Dami', ' Bam', 243),
('Asap Rocky Ft. Drake, .2 Chainz, Kendrick Lamar', 'Problems', 244),
('Nicki Minaj', ' Chung Li', 244),
('N.E.R.D. Ft. Rihanna', ' Lemonade', 244),
('Tyga Ft. Offset', ' Taste', 244),
('', ' Icy Girl-Saweetie Ft. Kehlani', 244),
('Ty Dolla Sign', ' Ex', 244),
('Kendrick Lamar Ft. Sza', ' All The Stars', 244),
('Rita Ora Ft. Cardi B, ', ' Girls', 244),
('Hoodcelebrityy', 'Walking Trophy', 245),
('Ed Sheeran', ' Shape Of You', 245),
('Tory Lanez', ' Luv', 245),
('Luis Fonzi Ft. Justin Bieber, Daddy Yankee', ' Despacito', 245),
('Jason Derulo Ft. Nicki Minaj', ' Swalla', 245),
('The Weeknd', ' Star Boy', 245),
('Kid Ink Ft. Chris Brown', ' Main Chick', 245),
('Tyga', ' Rack City', 245),
('', ' Dat Sexy Bod', 245),
('Adele', 'Hello', 246),
('Jay-Z Ft. Alicia Keys', ' Empire State Of Mind', 246),
('Bazzi', ' Mine', 246),
('Khalid Ft. Rae Sremmurd & Lil Yachty', ' Young Dumb & Broke', 246),
('Dorrough', ' Ice Cream Paint Job', 246),
('Migos', ' Stir Fry', 246),
('Childish Gambino', ' Redbone', 246),
('Mary J. Blige', ' Family Affair', 246),
('', ' Why You Always Hatin\'', 246),
('Full Force', 'Ain\'T My Type Of Hype', 247),
('Lionel Richie', ' All Night Long', 247),
('The Whispers', ' Rock Steady', 247),
('Debarge', ' Rhythm Of The Night', 247),
('Human Leauge', ' Don\'T You Want Me', 247),
('Madonna', ' Lucky Star', 247),
('Whitney Houston', ' How Will I Know', 247),
('Midnight Star', ' Midas Touch', 247),
('Kool And T', ' Fresh', 247),
('Camila Cabello', 'Crying In The Club', 248),
('G', ' Him And I', 248),
('Wiz Khalifa Ft. Ty Dolla Sign', ' Something New', 248),
('Migos', ' Stir Fry', 248),
('Sob X Rbe Ft. Yhung T.O.', ' Anti', 248),
('Jacquees Ft. Dej Loaf', ' At The Club', 248),
('Drake', ' Nice For What', 248),
('Jidenna Ft. Kendrick La', ' Classic Man', 248),
('2 Chainz Ft. Kanye West', 'Birthday Song', 249),
('Migos Ft. Carbi B. & Nicki Minaj', ' Motorsport', 249),
('Goldlink', ' Crew', 249),
('Fetty Wap Ft. Monty', ' My Way', 249),
('Silento', ' Watch Me', 249),
('Ayo & Teo', ' Rolex', 249),
('Kendrick Lamar', ' Humble', 249),
('Yo Gotti Ft. Nicki Minaj', ' Rake It Up', 249),
('Lil Uzi Vert', ' Xo Tour Lif3', 249),
('Maroon 5 Ft. Asap Rocky', 'Whiskey', 250),
('Adrian Marcel Ft. Sage The Gemini', ' 2Am', 250),
('Z Ft. Fetty Wap', ' Nobody Does It Better', 250),
('Jidenna', ' Classic Man', 250),
('Bluey', ' Where The Party At?', 250),
('B.O.B. Ft. 2 Chainz', ' Headbandz', 250),
('Baby Bash Ft. Sean Kingston', ' What Is It', 250),
('Asap Rock', ' Problems', 250),
('Block Boy Ft. Drake', 'Look Alive', 251),
('Young Gotti Ft. Nicki Minaj', ' Rake It Up', 251),
('Cardi B. Ft. Bad Bunny & J. Balvin', ' I Like It', 251),
('Travis Scott', ' Butterfly Effect', 251),
('Yfn Lucci Ft. Offset', ' Boss Life', 251),
('Miguel', ' Sky Walker', 251),
('Nf', ' Let Yo Down', 251),
('21 Savage', ' Bank Account', 251),
('G-', ' 1942', 251),
('Sir Mix A Lot', 'Posses On Broadway', 252),
('Eazy-E', ' Boyz In The Hood', 252),
('The Pharcyde', ' Passin Me By', 252),
('Mc Lyte', ' Cha,Cha,Cha', 252),
('Kool Moe Dee', ' Wild, Wild West', 252),
('B.D.P.', ' My Philosophy', 252),
('Special Ed', ' I Got It Made', 252),
('Tribe Called Quest', ' Can I Kick It', 252),
('Biz Mar', ' Nobody Beats The Biz', 252),
('Tribe Called Quest', 'Award Tour', 253),
('2 Pac Ft. Snoop Dogg', ' Amerikas Most Wanted', 253),
('Method Man Ft. Mary J. Blige', ' You\'Re All I Need', 253),
('Outkast', ' Atliens', 253),
('', ' Loungin\' [Who Do You Luv] Â€“ L.L. Cool J. Ft. Total', 253),
('Notorious B.I.G.', ' Juicy', 253),
('Ice Cube Ft. Mack 1', ' You Can Do It', 253),
('Jay-Z', 'Girls, Girls', 254),
('Outkast', ' So Fresh So Clean', 254),
('Lil Wayne Ft. Bobby Valentino', ' Mrs. Officer', 254),
('Notorious B.I.G.', ' Big Poppa', 254),
('Field Mob', ' Sick Of Being Lonley', 254),
('Jt Money Ft. Sole', ' Who Dat', 254),
('Camaron Ft. Jewelz Santana', ' Hey Ma', 254),
('Eve Ft. Gwen ', ' Let Me Blow Your Mind', 254),
('Dr. Dre Ft. Snoop Dogg', 'Let Me Ride', 255),
('Notorious B.I.G', ' One More Chance', 255),
('L.L. Cool J.', ' Doin\' It', 255),
('Kriss Kross', ' Tonites Da Nite', 255),
('Da Brat', ' Give To You', 255),
('Criag Mack', ' Flava In Ya Ear', 255),
('Run D.M.C.', ' Down With The King', 255),
('Das Efx', ' They Want Efx', 255),
('Gang Starr Ft. Ni', ' Dwyck', 255),
('Juvenile', 'Back That Hang Up', 256),
('Hot Boys Ft. Big Tymers', ' I Need A Hot Girl', 256),
('T.I.', ' Bring Em\' Out', 256),
('Ying Yang Twins', ' Salt Shaker', 256),
('Nelly Ft. City Spud', ' Ride Wit Me', 256),
('Ol\' Dirty Bastard Ft. Kelis', ' Got Your Money', 256),
('Mann Ft. 50 Cent', ' Buzzin [Remix]', 256),
('Fatman', ' Be Faithful', 256),
('E-40 Ft. T-Pain', 'U & Dat', 257),
('Too Short', ' Shake That Monkey', 257),
('Ciara Ft. 50 Cent', ' Can\'T Leave Em\' Alone', 257),
('Fabolous Ft. Jermaine Dupri', ' Baby Don\'T Go', 257),
('Baby Bash Ft. Akon', ' Baby I\'M Back', 257),
('Heavy D & The Boyz', ' Nuttin But Love', 257),
('P.M. Dawn', ' Set A Drift On Memory Bliss', 257),
('', ' D', 257),
('E-40 Ft. T-Pain', 'U & Dat', 258),
('Too Short', ' Shake That Monkey', 258),
('Ciara Ft. 50 Cent', ' Can\'T Leave Em\' Alone', 258),
('Fabolous Ft. Jermaine Dupri', ' Baby Don\'T Go', 258),
('Baby Bash Ft. Akon', ' Baby I\'M Back', 258),
('Heavy D & The Boyz', ' Nuttin But Love', 258),
('P.M. Dawn', ' Set A Drift On Memory Bliss', 258),
('', ' D', 258),
('Fabolous Ft. Tamia', 'So Into You', 259),
('Baby Bash Ft. Sean Kingston', ' What Is It', 259),
('Rihanna', ' Rude Boy', 259),
('Jay-Z Ft. Amil, Ja Rule', ' Can I Get Aâ€¦', 259),
('50 Cent Ft. Olivia', ' Candy Shop', 259),
('City High Ft. Eve', ' Caramel', 259),
('Big Tymers Ft. Tateeze, Boo & Gotti', ' Ohh Yeah', 259),
('Lord ', ' De Ja Vu', 259),
('Ghosttown Dj\'S', 'My Boo', 260),
('2 Live Crew', ' Hoochie Mama', 260),
('Tag Team', ' Whoomp There It Is', 260),
('69 Boyz', ' Tootsie Roll', 260),
('', ' Da Dip Â€“ Freak Nasty', 260),
('Mc Shy-D', ' Shake It', 260),
('Run D.M.C.', ' It\'S Tricky', 260),
('Back Sir Mix A Lot', ' Baby Got', 260),
('Quad City Dj\'S', ' Ride The Train', 260),
('Dj Taz', ' That\'S Right', 260),
('Fat Joe Ft. Sahanti', 'What\'S Luv', 261),
('Ja Rule Ft. Lil Moe & Vita', ' Put It On', 261),
('Ashanti', ' Rock With You', 261),
('Shaggy', ' It Wasn\'T Me', 261),
('Skee-Lo', ' I Wish', 261),
('Salt N\' Peppa', ' Shoop', 261),
('Warren G. Ft. Nate Dogg', ' Regulate', 261),
('Snoop Dogg', ' What\'S My Name', 261),
('2 Pac Ft. Digital Unde', ' I Get Around', 261),
('The D.O.C.', 'Funky Enough', 262),
('The Dogg Pound', ' Let\'S Play House', 262),
('Warren G.', ' This D.J.', 262),
('Ice Cube', ' You Know How We Do It', 262),
('2Pac Ft. Dr. Dre', ' California Love', 262),
('Snoop Dogg', ' Gin & Juice', 262),
('The Pharcyde', ' Running Away', 262),
('Lighter Shade Of Borwn', ' On A Sunday Afternnon', 262),
('', ' Summer', 262),
('Tyrese', 'I Like Them Girls', 263),
('Tamia', ' So Into You', 263),
('Aaliyah', ' Rock The Boat', 263),
('Adina Howards', ' Freak Like Me', 263),
('Toni Braxton Ft. Foxy Brown', ' Your Making Me High', 263),
('R. Kelly', ' Happy People', 263),
('Maxwell', ' Sumthin, Sumthin', 263),
('Lucy Pearl', ' Dance Tonight', 263),
('Montell ', ' Get It On Tonight', 263),
('Robin S.', 'Show Me Love', 264),
('Crystal Waters', ' 100% Pure Love', 264),
('Cece Peniston', ' Finally', 264),
('Nightcrawlers', ' Push The Feelings', 264),
('Everything But The Girl', ' Tracies Room', 264),
('Everything But The Girl', ' Miss You', 264),
('Mark Morrison', ' Return Of The Mack', 264),
('The Bucketheads', ' The Bomb', 264),
('', ' Anyway', 264),
('Survivor', 'Eye Of The Tiger', 265),
('Bush', ' Machinehead', 265),
('Nirvana', ' Smells Like Teen Spirit', 265),
('Def Leppard', ' Photograph', 265),
('Metallica', ' Enter The Sand Man', 265),
('Guns N\' Roses', ' Sweet Child O\' Mine', 265),
('Ac/Dc', ' Shook Me All Night Long', 265),
('Pat Benetar', ' Hit Me With Your Best Shot', 265),
('', ' Jessies Gi', 265),
('Chainsmokers', 'Paris', 266),
('August Alsina ft. B.O.B.  & Yo Gotti', 'Numb', 266),
('Katy Perry ft. Skip Marley', 'Chained to the rhythm', 266),
('Beyonce ft. Sean Paul', 'Baby Boy', 266),
('wiz Khalifa ft. Charlie Puth', 'See you again', 266),
('Marian Hill', 'Down', 266),
('50 Cent', 'In da club', 266),
('Ed Sheeran', 'Shape of you', 266),
('', 'Ayo-', 266),
('Drake', 'Nice for what', 267),
('Calvin Harris ft. katy Perry & Pharrell', 'Feels', 267),
('Charlie Puth', 'Attention', 267),
('Syn Cole ft. MIO', 'Who are you', 267),
('Alan Walker ft. Noah Cyrus with Digital Farm Animals', 'All falls down', 267),
('Calvin Harris ft. Dua Lipa', 'One Dance', 267),
('Ed Sheeran', 'Perfect', 267),
('', 'Push th', 267),
('Kevin Lytle', 'Turn me on', 268),
('', 'One dance-Drake ft. Wizkid & Kyla', 268),
('Santana ft. The Product G&b', 'Maria, Maria', 268),
('Enrique Iglesias', 'Bailamos', 268),
('Cecila Cruz', 'La Vida Un Canaval', 268),
('Selena Y Kumbia King', 'Baila Esta Cumbia', 268),
('Shakira ft. Wyclef', 'Hips donâ€™t lie', 268),
('', 'Me Llamas (Remix) (C', 268),
('Marquess ft. Raybuka', 'Suavecito', 269),
('Nicky Jam ft. J. Balvin', 'X (Equis)', 269),
('CNCO', 'Mamita', 269),
('Winsin ft. Ozuna', 'Escapate conmigo', 269),
('J. Alvarez', 'De La Mia Personal', 269),
('Maluma', 'Felices los 4', 269),
('Reik ft Ozuna & Wisin', 'Me Niego', 269),
('Daddy Yankee ft. Lil Jon & Pitbull', 'Gasolina', 269),
('Ric', 'Fiebre', 269),
('Maroon 5', 'Sugar', 270),
('Walk the Moon', 'Shut up & dance', 270),
('Disclosure', 'Latch', 270),
('Wiz Khalifa ft. Charlie Puth', 'See you again', 270),
('Jason Derulo', 'Trumpets', 270),
('Notorious B.I.G.', 'Big Poppa', 270),
('Ed Sheeran', 'Thinking out loud', 270),
('Rihanna', 'Umbrella', 270),
('Ariana Grande ft. The Weeknd', 'Love me harder', 270),
('', 'Cra', 270),
('Rihanna', 'Donâ€™t stop the music', 271),
('Justin Timberlake', 'Canâ€™t stop the feeling', 271),
('The Weeknd', 'Star Boy', 271),
('Calvin Harris ft. Dua Lipa', 'One dance', 271),
('Avicii ft. Rita Ora', 'Lonely together', 271),
('The Chainsmokers', 'Paris', 271),
('Tove Lov', 'Habbits', 271),
('Ed Sheeran', 'Castle on the hill', 271),
('', 'Rocketeer', 271),
('Janet Jackson', 'Got til itâ€™s gone', 272),
('702', 'Where my girls at', 272),
('T.L.C.', 'Creep', 272),
('Soul 4 Real ft. Heavy D.', 'Candy Rain', 272),
('Mary J. Blige ft. Notorious B.I.G.', 'Real Love', 272),
('Mario ft. Biz markie', 'Just a Friend 2000', 272),
('Jagged Edge ft. Nelly', 'Where the party at', 272),
('My', 'Case of the ex', 272),
('Jennifer Lopez ft. Ja rule', 'Iâ€™m real', 273),
('Craig david', '7 days', 273),
('3LW', 'Feelinâ€™ you', 273),
('Riahnna ft. Jay-Z', 'Umbrella', 273),
('Lauryn Hill', 'Canâ€™t take my eyes off you', 273),
('Ashanti', 'Happy', 273),
('Eve ft. Gwen Stefani', 'Let me blow your mind', 273),
('Nelly', 'E.I.', 273),
('Chingy', 'Right thurr', 273),
('R. Kelly ', 'Fiesta', 273),
('Stephanie Mills', 'Puttinâ€™ a rush on me', 274),
('Nu Shooz', 'Point of no return', 274),
('Cameo', 'Back and forth', 274),
('The Temptations', 'Treat her like a lady', 274),
('Alisha', 'Baby Talk', 274),
('Regina', 'Baby love', 274),
('Evelyn â€œChampagneâ€ King', 'Iâ€™m in love', 274),
('Billy Ocean', 'Nights [ feel like getting down]', 274),
('', 'K', 274),
('Gucci Mane ft. Young Jeezy', 'Icy', 275),
('David Banner', 'Play', 275),
('Bubba Sparxxx', 'Ms. New Booty', 275),
('E-40 ft. T-Pain & Kandi', 'U & dat', 275),
('Too Short', 'Shake that monkey', 275),
('Chris Brown ft. Julez Santana', 'Run it', 275),
('Khia', 'My Neck, my back', 275),
('Missy Elliot', 'Work it', 275),
('Ying Yang Twins', 'Salt shaker', 275),
('', 'Ge', 275),
('Micheal Mc Donald', 'I keep forgettin', 276),
('Warren G. ft. Nate Dogg', 'Regulate', 276),
('Mtume', 'Juicy fruit', 276),
('Notorious B.I.G', 'Juciy', 276),
('Dennis Edwards ft Siedah Garrett', 'DonÃ¢Â€Â™t look any further', 276),
('LilÃ¢Â€Â™ Wayne', 'Way of life', 276),
('Toto', 'Africa', 276),
('Ryan Leslie', 'How it was supposed to be', 276),
('', 'W', 276),
('Bobby Brown', 'Rock witcha', 277),
('Aaliyah', 'At your best', 277),
('Tony, Tonie, Tone', 'Whatever you want', 277),
('Usher', 'You make me wanna', 277),
('R. Kelly', 'Your bodyâ€™s calling', 277),
('Jodeci', 'Come & talk to me', 277),
('Xscape', 'Just kickin it', 277),
('T.L.C.', 'Waterfalls', 277),
('Tevin Campbell', 'Can we talk', 277),
('', 'Touch me, Tease me-', 277),
('Level 43', 'Something about you', 278),
('Bill Medley & Jennifer Warnes', 'Time of my live', 278),
('Simple Minds', 'DonÃ¢Â€Â™t you forget about me', 278),
('David Bowie', 'LetÃ¢Â€Â™s Dance', 278),
('Johnny Kemp', 'Just got paid', 278),
('Tony, Tonie, Tone', 'Feels good', 278),
('Madonna', 'Get into the groove', 278),
('', 'Heaven is a place ', 278),
('BURNS ft Maluma & Rae Sremmurd', 'Hands on me', 279),
('Christina Aguilera', 'Genie in a bottle', 279),
('Fat Joe n Remy Ma ft French Montana', 'All the way up', 279),
('Culprit', 'Closer still', 279),
('Dj Snake ft. Lauv', 'A different way', 279),
('Wayne Wonder', 'No letting go', 279),
('Clean Bandit ft Sean Paul &', 'Rockabye', 279),
('Hall & Oates', 'Private eyes', 280),
('Kingsmen', 'Louie', 280),
('Buster Poindexter', 'Hot', 280),
('jimmy buffet', 'Margaritaville', 280),
('', 'Sweet Carolina-Neil Diamond', 280),
('Gary Glitter', 'Rock n Roll pt2.', 280),
('Billy Joel', 'Uptown girl', 280),
('Paul Simon ft. Chevy Chase', 'You can call me Al', 280),
('B-52â€™s', 'Love shack', 280),
('', 'Build me u', 280),
('Bazzi', 'Mine', 281),
('Charlie Puth ft. Kehlani', 'Done for me', 281),
('Calvin Harris ft. Dua Lipa', 'One dance', 281),
('The Egales', 'Hotel California', 281),
('Tiesto & Dzeko ft. Preme & Post Malone', 'Jackie Chan', 281),
('Magic!', 'Rude', 281),
('Calvin Harris ft. Katy Perry & Pharrell', 'Feels', 281),
('Imagine ', 'Whatever it takes', 281),
('The Jackson 5', 'ABC', 282),
('Kansas', 'Dust in the wind', 282),
('Stevie Wonder', 'Supserstition', 282),
('Abba', 'Dancing queen', 282),
('Marvin Gaye', 'Whatâ€™s going on', 282),
('The Temptations', 'My girl', 282),
('The Bee Gees', 'Staying alive', 282),
('The Four Seasons', 'Oh what a night', 282),
('Wild Cherry', 'Play That Funky Music', 282),
('The Cover Girls', 'My heart skips a beat', 283),
('Lisa, Lisa & Cult Jam', 'I wonder if I take you home', 283),
('Sweet Sensation', 'Take it while itâ€™s hot', 283),
('Corina', 'Temptations', 283),
('George Lamond', 'Bad of the heart', 283),
('Expose', 'Point of no return', 283),
('Stevie B.', 'Dreaminâ€™ of love', 283),
('', 'Iâ€™ve been thi', 283),
('Junior', 'Mama used to say', 284),
('Kool & The Gang', 'Get down on it', 284),
('Indeep', 'Last night a dj saved my life', 284),
('Prince', 'Kiss', 284),
('Patrice Rushin', 'Forget me nots', 284),
(' Evelyn ÃƒÂ¢Ã‚Â€Ã‚Âœ ChampagneÃƒÂ¢Ã‚Â€Ã‚Â King', 'Love come down', 284),
('Billy Ocean', 'Caribbean queen', 284),
('Jan', 'When I think of you', 284),
('Daft Punk', 'One more time', 285),
('Bingo Players', 'Cry', 285),
('Bruno mars', 'Thatâ€™s what I like', 285),
('David Guetta ft. Sia', 'Titanium', 285),
('Rihanna', 'Only girl', 285),
('Post Malone ft. Quavo', 'Congratulations', 285),
('Avicii', 'Hey Brother', 285),
('Bob Sinclair ft. Steve Edwards', 'World hold on', 285),
('J. Balvin n Wi', 'MI Gente', 285),
('Soulja Boy', 'Crank that', 286),
('Huey', 'Pop lock it , drop it', 286),
('Shop Boyz', 'Party like a rock star', 286),
('Chingy ft. Ludacris, Snoop Dogg', 'Holidae inn', 286),
('Danity Kane', 'Show stopper', 286),
('Dem Franchize Boyz ft Lil Peanut n Charlay', 'Lean wit it, Rock wit it', 286),
('G 5 Boyz', 'Stanky legg', 286),
('', 'Cyclone', 286),
('Flo-Rida ft. Sia', 'Wild ones', 287),
('Don Omar Lucenzo', 'Danza Kuduro', 287),
('Marvin Gaye', 'Got to give it up', 287),
('Rihanna', 'This is what you came for', 287),
('Whitney Houston', 'I wanna dance with somebody', 287),
('Bruno Mars', 'Thatâ€™s what I like', 287),
('Justin Timberlake', 'Can\'t Stop The Feeling', 287),
('', 'Cake by the', 287),
('Flo-Rida ft. Sia', 'Wild ones', 288),
('Don Omar Lucenzo', 'Danza Kuduro', 288),
('Marvin Gaye', 'Got to give it up', 288),
('Rihanna', 'This is what you came for', 288),
('Whitney Houston', 'I wanna dance with somebody', 288),
('Bruno Mars', 'ThatÃ¢Â€Â™s what I like', 288),
('Justin Timberlake', 'Can\'t Stop The Feeling', 288),
('', 'Cake by ', 288),
('Brantley Gilbert', 'The weekend', 289),
('Blake Shelton', 'Iâ€™ll name the dogs', 289),
('Darius Rucker', 'If I told you', 289),
('Jason Aldean', 'They donâ€™t know', 289),
('Tim Mcgraw', 'Something like that', 289),
('Jon Pardi', 'Dirt on my boots', 289),
('Justin Moore', 'Somebody else will', 289),
('Dylan Scott', 'My girl', 289),
('', 'Thereâ€™s a gir', 289),
('Sam Hunt', 'House party', 290),
('Eric Church', 'Give me back my home town', 290),
('Blake Shelton', 'Honey bee', 290),
('Thomas Rhett', 'Make me wanna', 290),
('garth Brook', 'Friends in low places', 290),
('Toby Keith', 'I love this bar', 290),
('Kelsea Ballerini', 'Legends', 290),
('Rascal Flatts', 'Yours if you want it', 290),
('Eric ', 'High class', 290),
('Florida Georgia Line', 'Smooth', 291),
('Granger Smith', 'Happens like that', 291),
('Lady Antebellum', 'Heartbreak', 291),
('Michael Ray', 'Get to you', 291),
('Keith Urban', 'Female', 291),
('Jason Aldean', 'They donâ€™t know', 291),
('Brett Eldridge', 'The long way', 291),
('Billy Currington', 'Do I make you wanna', 291),
('', 'Everythingâ€™s gonna be', 291),
('Morgan Wallen ft Florida Georgia Line', 'Up down', 292),
('Russell Dickerson', 'Yours', 292),
('Cole Swindell', 'Middle of a memory', 292),
('Blake Shelton', 'She got away with words', 292),
('Kane Brown', 'Used to love you sober', 292),
('Jordan Rager ft. Jason Aldean', 'Southern boy', 292),
('Justin Moore', 'Kinda donâ€™t care', 292),
('Asap Rocky, Drake, Kendrick Lamar, 2 Chainz', 'Problems', 293),
('fetty wap ft. Remy Boyz', '679', 293),
('Travis Porter ft. Tyga', 'Ayy ladies', 293),
('V.I.C.', 'Wobble', 293),
('T.I. ft. Iggy zalea', 'Mediocre', 293),
('Big Sean ft. E-40', 'I donâ€™t fuck with you', 293),
('2 Chainz', 'Iâ€™m different', 293),
('Tyga', 'Rack City', 293),
('', 'How we d', 293),
('Asap Ferg ft. Nicki Minaj', 'Plain jane', 294),
('Bazzi', 'Mine', 294),
('G Eazy ft. Asap Rocky, Cardi B.', 'No limit', 294),
('Camila Cabello', 'Crying in the club', 294),
('Fifth Harmony ft. Fetty Wap', 'Flex', 294),
('Jidenna ft. Roman GianAurthur', 'Classic man', 294),
('Migos', 'Stiry Fry', 294),
('Drake', 'Nice for what', 294),
('', 'All the stars-', 294),
('Offset', 'Ric Flair drip', 295),
('Sage', 'College drop', 295),
('Tyga', 'Make it Nasty', 295),
(' Dj Mustard ft. Y.g. & Quavo', 'Want her', 295),
('Dj Snake ft. Lil Jon', 'Turn down for what', 295),
('Ciara ft. Petey Pablo', 'Goodies', 295),
('Aaliyah', 'Rock the boat', 295),
('Tinashe ft. School Boy Q', '2 On', 295),
('Liam Payne f', 'Strip that down', 295),
('Bruno Mars', 'Thatâ€™s what I like', 296),
('Ayo & Tao', 'Rolex', 296),
('Future', 'Fuck up some commas', 296),
('O.T. Genasis', 'Coco', 296),
('Calvin Harris', 'Summer', 296),
('Hechizeros Band', 'El Sonidito', 296),
('Lil Jon ft. offset & 2 Chainz', 'Alive', 296),
('Venga Boys', 'We like to party', 296),
('Yo. Gotti ft. Nicki Minaj', 'Rake it up', 296),
('', 'Cong', 296),
('Trap Beckham', 'Birthday chick', 297),
('Trey Songz ft. T.I.', '2 Reasons', 297),
('Hot Boyz', 'I need a hot girl', 297),
('Travis Porter', 'Ayy ladies', 297),
('Kendrick Lamar ft. sza', 'All the stars', 297),
('N.E.R.D. ft. Rihanna', 'Lemon', 297),
('Beyonce ft. Jay-Z', 'Crazy in love', 297),
('TWRK', 'Badinga', 297),
('Jeremih f', 'Donâ€™t tell emâ€™', 297),
('Lilâ€™ Dicky ft. Chris Brown', 'Freaky Friday', 298),
('Rihanna ft. Tory Lanez', 'Wild Thoughts', 298),
('Luis Fonsi & Daddy Yankee ft. Justin Bieber', 'Despacito', 298),
('G eazy ft. Asap Rocky & cardi B.', 'No limit', 298),
('Offset', 'Ric Flair drip', 298),
('Camila Cabello', 'Havana', 298),
('Trap Beckham', 'Birthday chick', 298),
('', 'Y', 298),
('Deorro ft. Elvis Crespo', 'Bialar', 299),
('Don Omar & Lucenzo', 'Danza kuduro', 299),
('Bruno Mars', 'Thatâ€™s what I like', 299),
('Calvin Harris ft. Migos & Frank Ocean', 'Slide', 299),
('Whitney Houston', 'I wanna dance with somebody', 299),
('Marvin Gaye', 'Got to give it up', 299),
('Justin Ti', 'I canâ€™t stop the feeling', 299),
('J. BOOG', 'LETâ€™S DO IT AGAIN', 300),
('COMMON KINGS ft. J BOOG & FIJI', 'NO OTHER LOVE', 300),
('SEAN PAUL ft. SASHA', 'SO IN LOVE', 300),
('MR. VEGAS', 'HEADS HIGH', 300),
('RIHANNA ft. DRAKE', 'WORK [DANCEHALL RMX]', 300),
('OMARION ft. CHRIS BROWN', 'POST TO BE [MURDER SHE WROTE BLEND]', 300),
('ED SHEERAN', 'SHAPE OF YOU', 300),
('', 'L', 300),
('Dj Snake ft. Bipolar Sunshine', 'Middle', 301),
('Camila cabello', 'Havana', 301),
('Reel 2 Real', 'I like to move it', 301),
('DJ Kass & Pitbull', 'Scooby doo pa pa', 301),
('Justin Timberlake', 'Rock your body', 301),
('Kanye West', 'Gold digger', 301),
('Lilâ€™ Dicky ft. Chris Brown', 'Freaky Friday', 301),
('Flo-rida ft. Maluma', 'Hola', 301),
('Prince Royce', 'El Clavo', 302),
('J. Balvin', 'Ambiente', 302),
('David Bisbal & Sebastian Yatra', 'A Partir De hoy', 302),
('Yandel ft, J. Balvin', 'Muy personal', 302),
('RKM & Ken-Y & Natti Natasha', 'Tonta', 302),
('Sebastian Yatra ft Luis Figueroa & Lary Over', 'Por perro', 302),
('Yandel', 'No pare', 302),
('Dad', 'La rompe corazones', 302),
('Sir Mix A Lot', 'Posses on Broadway', 303),
('', '', 303),
('Eazy', 'Boyz-N-The Hood', 303),
('', '', 303),
('The Pharcyde', 'Passinâ€™ me by', 303),
('', '', 303),
('Mc Lyte', 'Cha, Cha, Cha', 303),
('', '', 303),
('Kool Moe Dee', 'Wild, Wild West', 303),
('', '', 303),
('B.D.P.', 'My Philosophy', 303),
('', '', 303),
('Special ED', 'I got it made', 303),
('', '', 303),
('Tribe called Quest', 'Can I kick it', 303),
('', '', 303),
('Bi', 'Nobody beats the Biz', 303),
('Alok & Mario Bautista', 'Toda La Noche', 304),
('J. Balvin ft. Pharrell Williams, Bia & Sky', 'Safari', 304),
('Sia & Nicky Jam', 'Cheap Thrills [rmx]', 304),
('Karol G & shaggy', 'Tu pump um', 304),
('Mark B. ft. De La Ghetto', 'Como tu no hay', 304),
('Karol G.', 'Pineapple', 304),
(' Ana Mena, Becky G.', 'Ya es hora', 304),
('', 'We donâ€™', 304),
('Jermaine Dupri ft. Ludacris', 'Welcome to Atlanta', 305),
('Jay-Z', 'I just wanna love you', 305),
('Mystikal', 'Shake it fast', 305),
('N.O.R.E', 'Nothing', 305),
('The Clipse', 'Grindinâ€™', 305),
('Fabolous ft. Pharrell', 'Tit 4 tat', 305),
('Busta Rhymes ft. P. Diddy & Pharrell', 'Pass the Courvoisier', 305),
('S', 'Drop it like its hot', 305),
('', 'I dunno who you are', 306),
('', 'This is also needed ok j', 307),
('', 'coo', 308),
('', 'Power (Dirty) (Extended) G-Eazy ft Nef The Pharaoh & P-Lo', 309),
('', 'Taste (XXX) (Clean) (Extended) Tyga ft Offset', 309),
('HD ', '$ave Dat Money [Xtendz] ', 309),
('', 'GET LOW DIRTY YING YANG TWINS ', 309),
('Dirty Khia', 'My Neck My Back [Single] ', 309),
('', 'Icy Grl (XMiX Remix Video) Saweetie feat. Kehlani', 309),
('', 'PROBLEMS [DIRTY] A$AP ROCKY', 309),
('Dirty David Banner', 'Play ', 309),
('', 'I Wanna Love You (XMiX Remix Video) (Dirty Version) Akon feat. Snoop Dogg', 309),
('HD ', 'Want Her [Xtendz] ', 309),
('', 'FEELIN\' MYSELF [DIRTY] MAC DRE', 309),
('', 'Blow The Whistle (Dirty) (Single) Too Short', 309),
('', 'No Hoe (Dirty) (Single) D-Lo', 309),
('', 'name artist', 310),
('', '8/7/18 ', 310),
('', ' ', 310),
('', '', 310),
('', 'Be Careful (Clean) (Extended) Cardi B', 310),
('', '1942 (Clean) (Extended) G-Eazy ft Yo Gotti & YBN Nahmir', 310),
('', 'Apesh_t (Clean) (Extended) The Carters ft Offset & Quavo', 310),
('HD ', 'Hot Nigga [Xtendz] ', 310),
('', 'Bounce Back (Clean) (Extended) Big Sean', 310),
('HD ', 'Plain Jane Remix [Xtendz] ', 310),
('', 'Powerglide (XMiX Remix Video) Rae Sremmurd feat. Juicy J', 310),
('', 'Teach Me How To Dougie (Clean) (Extended) Cali Swag District', 310),
('', 'Good Life (Clean) (Single) Kanye West Ft. T. Pain ', 310),
('HD ', 'At The Club [Xtendz] ', 310),
('', 'ANTI [CLEAN] SOB X RBE ', 310),
('', 'name artist', 311),
('', '8/7/18 ', 311),
('', 'Freaky Friday (XMiX Xpress Dancehall Video Edit) Lil Dicky feat. Chris Brown', 311),
('', 'Mine (XMiX Xpress Dancehall Remix Video) Bazzi', 311),
('', 'Bed (XMiX Remix Video) (Dancehall Mix) Nicki Minaj feat. Ariana Grande', 311),
('', 'God\'s Plan (XMiX Xpress Dancehall Remix Video) Drake', 311),
('', 'Friends (XMiX Xpress Dancehall Remix Video) Marshmello & Anne-Marie', 311),
('', 'Shape Of You (XMiX Xpress Dancehall Remix Video) Ed Sheeran feat. Kranium', 311),
('', 'Walking Trophy (New Version) (Clean) (Extended) Hoodcelebrityy', 311),
('Clean Shakira ft Wyclef Jean', 'Hips Don\'t Lie (Moombahton Re-Drum) [DMS] ', 311),
('qHD ', 'No Letting Go (Scooter Moombahton Remix) [DMS] ', 311),
('1080 ', 'I Miss You (PeteDown Moomba Mix) [Xtendz] ', 311),
('', 'Move To Miami (XMiX Edit Video) Enrique Iglesias feat. Pitbull', 311),
('', 'Zooted (Clean) (Extended) Becky G ft French Montana & Farruko', 311),
('', 'Boo\'d Up (XMiX Remix Video) Ella Mai', 312),
('', 'Stir Fry (XMiX Remix Video) Migos', 312),
('Dirty Slim ft Yung Joc ', 'So Fly [Xtendz] ', 312),
('No Hype) [DMS] ', 'Closer (DJ Scooter Re-Drum ', 312),
('HD ', '679 [Single] ', 312),
('', 'PUT ME ON SOMETHING (CLEAN) P-LO | E-40', 312),
('', 'The Light (Clean) (Extended) Jeremih & Ty Dolla $ign', 312),
('HD ', 'All Falls Down [Snipz] ', 312),
('', 'IN MY FEELINGS [DJ READY ROCK XMIX REMX EDIT] DRAKE', 312),
('', 'Wild Thoughts (XMiX Remix Video) DJ Khaled feat. Rihanna & Bryson Tiller', 312),
('', 'No Brainer (Clean) (Extended) DJ Khaled ft Justin Bieber, Chance The Rapper & Quavo', 312),
('In My Feelings', 'Drake ', 321),
('Wild Thoughts', 'DJ Khaled ft Rihanna ', 321),
('Havana', 'Camila Cabello ', 321),
('Shape Of You', 'Ed Sheeran ', 321),
('No Diggity', 'Blackstreet ', 321),
('I Like Me Better', 'Lauv ', 321),
('Work It', 'Missy Elliot ', 321),
('Rock Around The Clock', 'Bill Haley & His Comets ', 321),
('Starboy', 'The Weeknd ', 321),
('No Brainer', 'DJ Khaled ft Justin Bieber, Chance the Rapper, Quavo ', 321),
('Delicate', 'Taylor Swift ', 321),
('Grindin\'', 'Clipse ', 322),
('It\'s Like That', 'Mariah Carey ft. Jermaine Dupree & Fatman Scoop ', 322),
('Clap Back', 'Ja Rule ', 322),
('Welcome to Atlanta Remix', 'Jermaine Dupree ft. P. Diddy, Murphy Lee, Snoop Dogg ', 322),
('Oye Mi Canto', 'N.O.R.E. ft. Nina Sky ', 322),
('Gasolina', 'Daddy Yankee ', 322),
('You Gets No Love', 'Faith Evans ', 322),
('Snake', 'R. Kelly ', 322),
('Just A Lil Bit', '50 Cent ', 322),
('Where The Party At Remix', 'Jagged Edge ', 322),
('If I Could Go', 'Angie Martinez ', 322),
('Get Right Remix', 'Jennifer Lopez ft. Fabolous ', 322),
('Lay Low', 'Snoop Dogg ft. Nate Dogg ', 322),
('Nothin\'', 'N.O.R.E. ft. Pharrell ', 322),
('When The Last Time', 'Clipse ft. Kelis & Pharrell ', 322),
('Pon De Replay Remix', 'Rihanna ', 322),
('Like Glue', 'Sean Paul ', 322),
('Don\'t Say Nuthin\'', 'The Roots ', 322),
('Beautiful', 'Snoop Dogg ft. Pharrell & Charlie Wilson ', 322),
('Hate It Or Love It', 'The Game ft. 50 Cent ', 322),
('I Need A Girl Part 2', 'P. Diddy ft. Ginuwine ', 322),
('Badd', 'Ying Yang Twins ft. Mike Jones ', 322),
('Freaky Friday', 'Lil Dicky ft. Chris Brown ', 323),
('Finesse', 'Bruno Mars ft. Cardi B ', 323),
('Chantaje', 'Shakira ft. Maluma ', 323),
('Feels x Something Just Like This', 'Calvin Harris ft. Pharrell, Big Sean, Katy Perry x Chainsmokers ', 323),
('The Middle x Mi Gente', 'Maren Morris x J Balvin y Willy William ', 323),
('Friends', 'Marshmello ft. Anne-Marie ', 323),
('No Promises x What Lovers Do', 'Demi Lovato x Maroon 5 ', 323),
('What Lovers Do x No Promises', 'Maroon 5 x Demi Lovato ', 323),
('No Tears Left To Cry x One Kiss', 'Ariana Grande x Dua Lipa ', 323),
('One Kiss x My Love', 'Dua Lipa x Martin Solveig ', 323),
('Can\'t Stop This Feeling x Intoxicated', 'Justin Timberlake x Martin Solveig ', 323),
('', 's', 324),
('', 's', 325),
('', 'sobe it', 326),
('', 'abcdfgh', 327),
('Ginuwine', 'Pony ', 328),
('Cardi B', 'Bodak Yellow (Pony Remix) ', 328),
('Driicky Graham', 'Snap Backs and Tattoos ', 328),
('Jay-z & Kanye West', 'N---as in Paris ', 328),
('DRAM ft Lil Yachty', 'Broccoli ', 328),
('Flo Rida ft Sage The Gemini', 'GDFR ', 328),
('Migos ft Drake', 'Walk It Talk It ', 328),
('Fetty Wap', 'Trap Queen ', 328),
('Skrillex & Rick Ross', 'Purple Lamborghini ', 328),
('Trey Songz ft Nicki Minaj', 'Bottoms Up ', 328),
('Kendrick Lamar', 'Humble ', 328),
('Yo Gottie & Mike Will Made-it ft Nicki Minaj', 'Rake it Up ', 328),
('DJ Khaled ft Ludacris, T-Pain, Rick Ross & Snoop', 'All I do is Win ', 328),
('Katy Perry vs Pitbull & Ying Yang Twins', 'California Girl Shake ', 329),
('Nicki Minaj', 'Va Va Voom ', 329),
('Yazz', 'Don\'t Go ', 329),
('Dead or Alive', 'You Spin Me Right Round ', 329),
('Berlin', 'No More Words ', 329),
('Rick Springfield', 'Jesse\'s Girl ', 329),
('Journey', 'Separate Ways ', 329),
('Eddie Murphy', 'Party All The Time ', 329),
('Michael Jackson', 'Beat It ', 329),
('The Killers', 'Somebody Told Me ', 329),
('Blondie', 'Call Me ', 329),
('Flock Of Seagulls', 'I Ran ', 329),
('Wham', 'Wake Me Up ', 329),
('Kenny Loggins', 'Danger Zone ', 329),
('Spice Girls', 'Say You\'ll Be There ', 330),
('Backstreet Boys', 'Everybody ', 330),
('Britney Spears', 'I\'m a Slave 4 U ', 330),
('Oran Juice Jones', 'The Rain ', 330),
('Bobby Brown', 'My Prerogative ', 330),
('Simple Minds', 'Don\'t You Forget About Me ', 330),
('Justin Timberlake', 'Can\'t Stop The Feeling ', 330),
('The Cardigans', 'Lovefool ', 330),
('Blondie', 'Heart of Glass ', 330),
('Cameo', 'Word Up ', 330),
('Alice Merton', 'No Roots ', 330),
('No Doubt', 'Hella Good ', 330),
('Blaque ft JC Chasez', 'Bring it All To Me ', 331),
('Lloyd Banks ft Avant', 'Karma ', 331),
('Iyaz', 'Replay ', 331),
('Aaliyah ', 'Back & Forth ', 331),
('Adina Howard', 'Freak Like Me ', 331),
('TLC', 'No Scrubs ', 331),
('Billie Lawrence ft MC Lyte', 'Come On ', 331),
('Soul IV Real', 'Candy Rain ', 331),
('Shanice', 'I Love Your Smile ', 331),
('Mario', 'Let Me Love You ', 331),
('Mark Morrisson', 'Return of The Mack ', 331),
('Ruff Endz', 'No More ', 331),
('Tatyana Ali', 'Daydreaming ', 331),
('Oasis', 'Wonderwall ', 332),
('Good Charlotte ', 'The Anthem ', 332),
('Red Hot Chili Peppers', 'Can\'t Stop ', 332),
('Kansas', 'Dust In The Wind ', 332),
('Joan Jett & The Blackhearts', 'I Love Rock n Roll ', 332),
('Evanescence', 'Bring Me To Life ', 332),
('Sum 41', 'Fat Lip ', 332),
('Linkin Park', 'In The End ', 332),
('Survivor', 'Eye Of The Tiger ', 332),
('Queen', 'Another One Bites The Dust ', 332),
('Motley Crue', 'Dr Feelgood ', 332),
('AC/DC', 'Shook Me All Night Long ', 332),
('The Outfield', 'Your Love ', 332),
('Memories', 'Vintage Culture & Clubbers ', 373),
('Don\'t Stop The Music (Future House Bootleg)', 'Rihana ', 373),
('Body Movin (Wax Motif Remix)', 'Tommy Trash ', 373),
('Stay vs We Come 1 (Bren F Future House Mashup)', 'Zedd ft. Alessia Cara vs Faithless ', 373),
('Flow', 'MATRODA ', 373),
('Bedroom Floor (Jason Reilly & MDB Remix)', 'Liam Payne ', 373),
('Know No Better (Kameo Remix)', 'Major Lazer ft. Travis Scott, Camila Cabello & Quavo ', 373),
('', 'Martin Solveig ft. Tkay Maidza ', 373),
('(SvenTM Remix)', 'Do It Right ', 373),
('Missing You (Tchami Remix)', 'Tchami ft. AC Slater & Kaleem Taylor ', 373),
('Make Me (Marc Stout & Tony Arzadon Remix)', 'Britney Spears ft. G-Eazy ', 373),
('Ibiza 77', 'Oliver Heldens ', 373),
('What\'s Up', 'Lucky Charms ', 373),
('Love Vibrations', 'HI-LO & Dada Life ', 373),
('Lifted', 'Cazztek ', 373);
